###
### Automation Setup
###
### Parameters are:
###   - replicated_automation_settings_file
###   - replicated_automation_conf_file
###   - replicated_automation_extra_files
###

# TODO: add ipv6 support

- name: Check if settings file should be copied
  local_action: stat path='{{replicated_automation_settings_file}}'
  register: settings
  when: replicated_automation_settings_file is defined

- name: Copy settings file
  copy:
    dest: "/tmp/replicated_settings.conf"
    src: '{{replicated_automation_settings_file}}'
    owner: root
    group: root
    mode: "ugo=r"
  when:
  - replicated_automation_settings_file is defined
  - settings.stat.exists
  no_log: false
  become: yes
  become_method: sudo

- name: Check if replicated conf file should be copied
  local_action: stat path='{{replicated_automation_conf_file}}'
  register: conf_file
  when: replicated_automation_conf_file is defined

- name: Copy Replicated config file
  copy:
    dest: "/etc/replicated.conf"
    src: '{{replicated_automation_conf_file}}'
    owner: root
    group: root
    mode: "ugo=r"
  when:
  - replicated_automation_conf_file is defined
  - conf_file.stat.exists
  no_log: false
  become: yes
  become_method: sudo

- name: Copy extra files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ replicated_automation_extra_files }}"
  when: replicated_automation_extra_files is defined

###
### Install Replicated
###
### Parameters are:
###   - replicated_private_address
###   - replicated_public_address
###   - replicated_http_proxy_address
###   - replicated_https_proxy_address
###   - replicated_noproxy
###   - replicated_docker_version
###   - replicated_install replicated|operator; replicated is the default
###

###
### Run the docker install for the operating system
###

- name: Install Docker
  include: docker/pre/{{ ansible_distribution }}.yml
  when: replicated_install_docker

###
### Install Replicated
###

- name: Installing Replicated Containers
  include: scheduler/replicated/replicated.yml
  when: replicated_install is not defined or replicated_install == "replicated"

###
### Install Replicated Operator
###

- fail:
    msg: "Operator only install missing required replicated_daemon_address parameter"
  when: replicated_daemon_address is not defined and replicated_install is defined and replicated_install == "operator"

- name: Prep operator install env vars
  set_fact:
    replicated_daemon_endpoint: '{{ replicated_daemon_address | default(ansible_default_ipv4.address) }}:9879'
    replicated_daemon_host: '{{ replicated_daemon_address | default(ansible_default_ipv4.address) }}'

- name: Installing Replicated-Operator
  include: scheduler/replicated/operator.yml
  when: replicated_install is not defined or replicated_install == "operator" or replicated_install == "replicated"
